  apiVersion: argoproj.io/v1alpha1
  kind: AppProject
  metadata:
    name: infrastructure
    namespace: argocd
  spec:
    description: "Infrastructure add-ons managed by Argo CD ApplicationSet"
    clusterResourceWhitelist:
    - group: '*'
      kind: '*'
    destinations:
    - namespace: '*'
      server: '*'
    sourceRepos:
    - "https://github.com/TechTalk-With-Nathan/platform-gitops"
    - "https://charts.jetstack.io"
    - "https://prometheus-community.github.io/helm-charts"
    - "https://grafana.github.io/helm-charts"
    - "https://bitnami-labs.github.io/sealed-secrets"
    - "https://kubernetes-sigs.github.io/external-dns"
    - "https://helm.cilium.io"