apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
- restart-hook.yaml

patches:
- path: patch-argocd-cm.yaml
  target:
    kind: ConfigMap
    name: argocd-cm
    namespace: argocd