apiVersion: v1
kind: ServiceAccount
metadata:
  name: hook-restart-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hook-restart-role
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get","patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hook-restart-rb
subjects:
- kind: ServiceAccount
  name: hook-restart-sa
roleRef:
  kind: Role
  name: hook-restart-role
  apiGroup: rbac.authorization.k8s.io