---
apiVersion: batch/v1
kind: Job
metadata:
  name: argocd-restart-hook-placeholder
  generateName: argocd-restart-hook-
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      serviceAccountName: hook-restart-sa
      containers:
      - name: restart
        image: bitnami/kubectl:latest
        command:
        - sh
        - -c
        - |
          kubectl rollout restart deployment argocd-repo-server &&
          kubectl rollout restart deployment argocd-server   # optional but often useful
      restartPolicy: OnFailure