apiVersion: v1
kind: Service
metadata:
  name: bind9
  namespace: external-dns
spec:
  selector:
    app: bind9
  ports:
  - name: dns-udp
    port: 53
    protocol: UDP
    targetPort: 53
    nodePort: 30053
  - name: dns-tcp
    port: 53
    protocol: TCP
    targetPort: 53
    nodePort: 30053
  type: NodePort