apiVersion: v1
kind: ConfigMap
metadata:
  name: bind-zone
  namespace: external-dns
data:
  k8s.zone: |
    $TTL 60
    @   IN SOA ns.example.com. root.example.com. (
            2026031401
            60
            60
            60
            60 )

        IN NS ns.example.com.

    ns  IN A 127.0.0.1