---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rfc2136-keys
  namespace: external-dns
spec:
  encryptedData:
    rfc2136-tsig-keyname: AgADd4eHF//IHo1edENoAI0qlnBZkOB/C7aDewkg9sWb19i5cdif68GOfbaeaC6rrNe40x4Q8rE4hIKHHDS7NDCLAxLuu4FX+HsksyNTsFG4HKh8+5O72eiAmy9nqn9UJstGQU2xqfg0WSIvhyYSwRohPQrYey95329fJi3Wc69NPtTpb0AP+HmMuQ1VH/PNFaFzkW+eyetz5DDGHLPXUSkzFng4G4CiQhFtWJuP2c7+PbHeOSDSnJqkrpTpjQS4Bk3C3zQNP22w/QKzRWNPF1l9jG2RboI0E1fzQWlQqKU1NbEbWDSYuD8ZM6BGiEgywc4NVPrmghIyd6HbqrY7QY7YHH2fK/3OZIfT3qC4B/4pKjorJPJhQkW++6E5Qv0RJRo4gjCzIjq41zFL0TpOh5VvularFcRljXDao4HtRUCwATQtnOuTF8ykgFnjmDGEefS21nAHmEO7hHUQd4C9LcDAvhXA5xxrA6XQix9Sk5tt8naXO1LOVIGnhijCeTrUbtUlojm7UdZOJAEPGuw2gEwSXcG18nme/y+WL/5DEKU32ETS7NU0+i62NeW9LFa/a0MDgHYG0yMMS3ryM5We2B1UbzCMDHUpGzvbKm57iaphy9imzKHt0KYy/9FsBU+F3taK0CrnwUuO8+aC+PXqWZXO26y4gI5mTWZSLfoEccpV7MipB3G6uLi4nmBW/ZyUlLc/ckqe1lYOCT/Qz3jmuJI=
    rfc2136-tsig-secret: AgBumJ1mYh3wKWuHf+uZbI/LU7kosRSrlgKOtFQihA4Z8B3oJvMPeUr9qt0idQKyJmEhNkfIEBXDKgVz9PP8+Rz3o8USw9DJ/u2Vcyx9GOaJzu5FEV6z8VsjEfN6lBxMMp26bSvKiP1OzKFk468xj+E2IDYGgi9y4mvfzQ4npeTsK6YRb4/MGCl3HUuQCXdw0YPjnKRJ9wI4pH600vWDvUM8QgYEZd8Arn+OB1LXKaLB+BXQve9lBNfPp29hFmxf+/5WcDPKX3AdmV04r3d5Qkuh6WFqaRHgSbgrmfuF/aYgi3BVggbqEnZLlpz102EDOoCRU3bH/L5DCzRkgfNpSk2igd2YTqtpWWepKbPgoz5hTK5F8meBu5haZhBGXQiJzdUBxIjM1c9VQ+NcImLNOpYUanOSJfpJsDcW7Sl0halAqECi/aMIqNqElaHSgpmhQ5Cy9LL3ne4DP0YOsyCqpt5uDSAq7wJF6I/+bHC8mj5Omk/Pgoj+auly6UV+5EdzAfizVsMmPJ8MtUtCqfUi9pjp+YnUKDMxMCCZ8DBJkF3+FGKb8TXhK48RH/fxNkQFTnsPp0RlLoXhuX6n0nfUb8hU8CAh/q5TMTGgiN1N5jzKmImTf9X6E8q70jWwUmh19ak6WdTR5Dg8RZzajBwz88VGCzRBTZPmFs4lgF6m6CPLigevT5IXcqOa018XIPnlkf0kr6uDo5LzEzmtGr+GREMtEMI0e55Tut6YWBOT2QsLrhISmcMwcyXTRq0BXQ==
  template:
    metadata:
      name: rfc2136-keys
      namespace: external-dns
    type: Opaque
