---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bind-tsig-key
  namespace: external-dns
spec:
  encryptedData:
    external-dns.key: AgAzTVm4xdaqhUqRtbKuwW88zOJEf7EJDJdRSn1DkO20uNy5E27vLb/RAmK6iaXK9uZqzGax6P775exSlA/jYMiWITd3ewCmllwxc3DgAAEHMxhHLELGYxt98F1APW9UStJKbeGxXg6m+400B2lRo5uCM2S2rCHaj+BiXYizZsIgK23VQXXL9B3Hu4NceUK+yYo3AoBGZgBX6ZaSRXMzj+gUYNGs2BqrXOnujq0IOqiV1BRgNH57gFov0ocyIX+9q2dIlP7+KmERLNGQKkX9YP1XDuoEMW2thJVbKNzvuGT3v/uCRsbMbB1605nmx5V0VXhj65aBlol1wEI3pHEMawUqUov4gLuZHKW6KdoDZF+V1zA1a5SOUyIm3oUSummJG8TqGxENZRJHW1MiDVYQC8V/QLyyAAX4AIbX5T4fPo8jdrDlJenuACdEE2hsVrYzQyY+POJ7axTKcYQcepoh7hr1s9LlxrC0ydw6wJ9KO8XAxmfFWGRrCYoX8De07cT9DV8b2iHbuNycEExlNNUO6IODEXJtupbggn7QPFbYv80nAESMdZPkC5wjuWqsdbYGhal7VYswRp+JtufDvHR1ggl1fdMMdab1+cUoo+QY7VN62l43rlcg6y6tKeGJPQF9Mh4ajME1Qb4bs/K22OD3oxE1O18ILNefZxG0iIv4eRZ2vItlDDeNPOFDzgT6/d+tXs9QV6iufjP16YbtICzTR2ON2y6FMavYlPArdkuDscx7AYEzXfqEzX3wxFwYORgca6973nbSmfzjmOhjEb3UFyKMqc6+ZxrG+dTCoTT2QB3V/2fUir+nRjEvP64vUIqmlYi8sQYVzHE8
  template:
    metadata:
      name: bind-tsig-key
      namespace: external-dns
