---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bind-tsig-key
  namespace: external-dns
spec:
  encryptedData:
    external-dns.key: AgB9Cta3ZFdxN0GgfamxG1YdVF4z9W3bN91Ot3xgjyVGHpXciWV2Kssv0DhUmbW+AmcIJnCQkonDB6FjN6a6MM8etaMarAz4yF4bFSCmUnq6MGbVGwSUMJJPckHeLO2dq65ZjqnjwwHe2k0SN/ymZhrMXdYiBaLjXF3CbO2AU36v3qN4UYDGHimed+JcZWcZ6E4yip5FyDGGlcYynpJkeJsehZ4btFRyqZyEK/YFs8JtWQfHosFhBfUg2vZgw+BPy+ZovVWNMEe0yXfmIKqwvYJxWraCGRByAhUJfRKatLHRmk/FEDbCCDCK1080cnXpQHTjouVxOD4Bcs/mIg2cTb1v1O52FHDkfQ+ftXWJJNC5tY/G9W+GelUV4O/MxeO4gT89lwd+KgNQRl7S5Kn9Hhd8lcKkUAY3P0Ihe3f7Cb8ZRxyIIZm7yjp618E25GW6verPX+KPaT5aibSam5DU7nThj9MjUAXL6tm/t3TOLBcF8GRzhQ4wtOs49dKNYDcUr4Ywx9y7f+5DAcSDGI7yDCEz7oSXSDqXCfOTvz1d3kLi7f7WpnabiXKz+aSfXq+4wdr78n7t2u906bvqjIV7MxlF+IA5/xCKY8/7Kl+x9DpQLBgzZ3Fi6l0aafbKrr7+6a2UuNklj+ftaktrB+7OWIaRN49zra/mIO84GVpEuOI6/gByzrGg6TocYbuq8dwpVnVRIZ3CbwALoRVcFzRP0vIs39ZAxF1wgEpnLiVJToUoVAFFjp3bml0RmqUWyrJwdBZL6liHVTfMcemx1edzisMQQ8EuyXtPf66u36ahboiZ5HN0rclrq+HiiStkQWDi2s+9QBIyQ+F+
  template:
    metadata:
      name: bind-tsig-key
      namespace: external-dns
