---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rfc2136-keys
  namespace: external-dns
spec:
  encryptedData:
    rfc2136-tsig-keyname: AgCFMZ1EaEXBxl7hyAqyy+l11Fk6I5/5VXhv9VhXZfNYKq9gZe/YXCYSXP3TU1BSwuWmqGFIZnT9T9WPY6U9Z1Ow8eN6QB+146NQg/XwSShLjYSauvEBSnKClJnr7pm2X8K4qvfcmH9SnWTlTbChx7BNJ3qbxkx84ydPhdi9SJKgBly3gb7kVXWLE9BD87pnTrcT+rYYvJSkPdBprMxUZMUOeSNmK+MBscNPvuivWU/jvcm9/wACiIPa0FPaF1LTrjyvZkqk9KRNFKY8851xJ798I7Nvh/El33FZ4Og+u/6436Gpq2xRV8FNt5Gdvxwj1csRrFzBkQq4NmqK/yGgpYPCumQ5/0uFLzm5ph0mbNAmjXu23tYy6VkU2bRc5eKiJ08pw6CDaF2yPNd/MWtf1X0sUA0b/1ugEoviHUqVcxKaKxsKhEPlpFhQq+M+NGD6OfxMf3rJaCflkchcAceP/tj9ne/VEkYkcBxxbbOgrM8f4LE2I5ZdgOFylYDv2CT4RaK9AV7bsqlaGn9Hv3gM22pI6YykH6Aa6APcc8DxgpT3Y6N5oyaWDBwEULW90fCWkykZ//7kuR2/vJhHc9bf2Fx2iEekCbK6C2GiC0zwIFTGiD9GNYWTAmOGKe1Zusccg6LZqPVT1tlZhLMH0UiBetAjWT2I59cW0335p1qO70w2w4nFfxx6cjLH6fux724YF4lXaWlzsC6h80OpwA==
    rfc2136-tsig-secret: AgA0q5+AoXbGMqQtXIUBSFodDA1Gef8EEq1fPQhwT5WydGtdbGZju+wAnOhZ3MRJx9BKDbG15aViIcsXR7uT8aUT11dDMs2rIWroqCu43TQ3jta4RLqXVmLJwLMCZiIwyimRxbC5HR2Av4c9V0JZqmCgfao3SX+RuFUXBcanfJQmkvVGWQuVmeAd9Lf9UcUw+LLyIJ8tU6n58TzKQpQ6lvbXrSkSrigeGl8BLGajX4ZliUoursZTU98OH+L/nqdqxXBpoH5LIzBly38+jaI5Dm+yJW1NS8/PrI4R3RfGCMg6qUfVaCgrmGfRhGcgxdO8kceJRNavnOnjG7mQTu3bxPK/Yf7Wd2SSC/+e2Fjd6lkGzdT3igzeYWtE2lN//tJNXtSFpIjiYDjaxL1KiKokhRkr/d6I7Q9eGhGuhBbeqH3l8UJPwNijk/eYRCrjrhhaVvq5Og++knaRAlVYm8Dl2nn/BIqYpUYeeWE16Nzo0yvqBPc0D10JSZO1u5ykK3usClyzmwkUgSnBcim0cGXR99joca2oIPQHHfjkVwpSAn71r/+aDogbhpR/2sqxMN+jWcFnnl+QLigS7BFoCgwO78ft0YiybWZxCaus72+hmjDENyKZM+YzEGovl78RBLlSLbAzFMxd94kgY+8ChWMl4wKNywBfwauBN9KRrkoSyqc6KROs8dPeEQilozHvHiENGUMk+827QmGYdPoBB60kngLt4DaGhbiDrKV9G1adlKz6VNtbHgxqgQMeGljrVg==
  template:
    metadata:
      name: rfc2136-keys
      namespace: external-dns
    type: Opaque
