apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infrastructure-helm
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - list:
        elements:

          - name: cert-manager
            namespace: cert-manager
            repoURL: https://charts.jetstack.io
            chart: cert-manager
            version: v1.19.2
            valuesPath: infrastructure/cert-manager/values.yaml
            wave: 1

          - name: loki
            namespace: observability
            repoURL: https://grafana.github.io/helm-charts
            chart: loki
            version: 6.53.0
            valuesPath: infrastructure/loki/values.yaml
            wave: 2

          - name: kube-prometheus-stack
            namespace: observability
            repoURL: https://prometheus-community.github.io/helm-charts
            chart: kube-prometheus-stack
            version: "82.1.0"
            valuesPath: infrastructure/kube-prometheus-stack/values.yaml
            wave: 1


  template:
    metadata:
      name: "{{.name}}"
      labels:
        app.kubernetes.io/part-of: infrastructure
      annotations:
        argocd.argoproj.io/sync-wave: "{{.wave}}"
    spec:
      project: infrastructure
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{.namespace}}"

      sources:
        - repoURL: "{{.repoURL}}"
          chart: "{{.chart}}"
          targetRevision: "{{.version}}"
          helm:
            valueFiles:
              - $values/{{.valuesPath}}
        - repoURL: "https://github.com/TechTalk-With-Nathan/platform-gitops"
          targetRevision: main
          ref: values
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
